### ISSUE TITLE
n0026这样写不算作弊么

### ISSUE THREAD

**Issue by jonirrings** [aylei/leetcode-rust#5]
https://github.com/aylei/leetcode-rust/blob/master/src/n0026_remove_duplicates_from_sorted_array.rs#L53

如题，还是说leetcode上是可以这么做的[滑稽]？

**Comment by aylei** [comment]
应该是作弊吧，我的评论在 LC 上被人踩死了【狗头】
主要是这题没啥意思。。就没好好做

**Comment by aylei** [comment]
可以提交 PR 2333
